### PR TITLE
Added skysend.ch and allthefiles.net

### LINKED ISSUE #68: Add new instances?
I would also add my instances. However, I have several and they are grouped together. I don't know how it makes the most sense to add them, individually? The instances can change over time. 
https://skysend.ch

### LINKED ISSUE #69: Add Instance
Hey gang.

I would like to add my instance.

https://allthefiles.net

### PR DESCRIPTION
**Pull request by tdulcet**
* Added ch.skysend.ch and de.skysend.ch as requested. Fixes #68
* Added allthefiles.net as requested. Fixes #69

Thanks @Skyfay and @TeamBarryBrowne for letting us know.

### CODE REVIEW

**Comment by Skyfay** [comment]
@tdulcet Thanks for adding. Would it be a good idea to add the main URL https://skysend.ch to the **Links/
Notes** in both instances?

**Comment by tdulcet** [comment]
> Would it be a good idea to add the main URL https://skysend.ch to the **Links/ Notes** in both instances?

Sure, I added a link as requested in e71ea4385aa49ab3963d1e744ffcc015ffce70c8. Let me know if you want any additional changes.

BTW, some of the text on your website is unreadable with the light mode (black text on a black background):
image

**Comment by Skyfay** [comment]
> Sure, I added a link as requested in

Thank you, perfect!

> BTW, some of the text on your website is unreadable with the light mode (black text on a black background):

Ah, never thought about the fact that there is a white mode. But yes, it gets it from the system. I'll probably have to fix that. Thanks for the info :)

**Comment by Skyfay** [comment]
> @Skyfay - The `support@skyfay.ch` e-mail address listed on your website does not work.

Thanks, should work now :)

**Pull request merged**
