### PR TITLE
Add send.cyberjake.xyz

### PR DESCRIPTION
**Pull request by Cyb3r-Jak3**
Adds `send.cyberjake.xyz`.
Didn't add the uptime robot check as I don't know how to

### CODE REVIEW

**Comment by tdulcet** [comment]
Thanks for the PR!

It looks like the maximum file size is 1 GiB not 10 GiB. Also, you need to keep that blank line below the table, as otherwise it will include the preceding line as part of the table...

We are planning to replace those Uptime Robot badges as they are not working (see #32), but for now here is the needed API key for your instance: `m794455795-2d6b721c8e5dfcc8dcdae877`

**Comment by Cyb3r-Jak3** [comment]
Made the changes. It is now actually 10 GB

**Comment by tdulcet** [comment]
@timvisee - Should I go ahead and merge this?

**Comment by timvisee** [comment]
> @timvisee - Should I go ahead and merge this?

For sure. Go for it! 😁

**Pull request merged**
